apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: SAS
  labels:
    failure-domain.beta.kubernetes.io/zone: AZ
  name: PVC_EVS_NAME
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-disk

