apiVersion: v1
kind: Service
metadata:
  name: svc-2
  labels:
    app: test-nginx-2
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 83ed8ac8-f694-4f08-b9e8-47b40ee609a5
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    kubernetes.io/elb.health-check-flag: 'on'
    kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
spec:
  selector:
    app: test-nginx-2
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-2
      targetPort: 80
      nodePort: 0
      port: 20002
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: ''

